# Site settings
title: Abigail Monson
header-img: img/home-bg.jpg
email: abigail.ann.monson@gmail.com
copyright_name: Your/Project/Corporate Name
description: "A place to learn all about Abigail Monson, that's me!"
baseurl: ""
url: "www.abigailmonson.me"
twitter_username: abigailmonson
github_username:  abbycakes207
facebook_username: Abigail Monson
email_username:  abigail.ann.monson@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
